remote_theme: mmistakes/minimal-mistakes

title: "ECON 3335: Urban and Regional Economics"
description: "St. Edward's University | Spring 2027"

author:
  name: "Chen Xu"
  email: "cxu@stedwards.edu"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
